Docs content for Go drivers and ORMs
nchandrappa/yugabyte-db pull request #3
Opened 2022-02-16 04:20 UTC by ashetkar

Docs content for Go drivers and ORMs as per the new template

2022-02-17 05:28 UTC, polarweasel requested changes
Some comments, some changes (most of which should be applied to all files)...

2022-02-17 05:28 UTC, polarweasel commented on docs/content/latest/drivers-orms/go/compatibility.md
> +| v4 |  2.8 (stable) | full
By the time this goes live, I'm pretty sure stable will be 2.12, and latest will be 2.13

2022-02-17 05:28 UTC, polarweasel commented on docs/content/latest/drivers-orms/go/_index.md
> +Following are the recommended projects for implementing Golang Applications for YugabyteDB YSQL API.
```suggestion

Following are the recommended projects for implementing Golang applications using the YugabyteDB YSQL API.
```

2022-02-17 05:28 UTC, polarweasel commented on docs/content/latest/drivers-orms/go/_index.md
> +## Build a Hello World App
Headings should be sentence case
```suggestion
## Build a hello world app
```

2022-02-17 05:28 UTC, polarweasel commented on docs/content/latest/drivers-orms/go/_index.md
> +section.
Please don't hard-wrap lines. One paragraph per line, or one sentence per line. Anything else makes diffs really ugly when you make changes later on!

Also, please use relative links, instead of absolute. The link I've put here is almost certainly incorrect, so fix it before you merge!
```suggestion
Learn how to establish a connection to your YugabyteDB database and begin simple CRUD operations using the steps in [Build an Application](../../../quick-start/build-apps/go/ysql-pgx) in the Quick Start section.
```

2022-02-17 05:28 UTC, polarweasel commented on docs/content/latest/drivers-orms/go/_index.md
> +## Pre-requisites for Building a Go Application
```suggestion
## Prerequisites
```

2022-02-17 05:28 UTC, polarweasel commented on docs/content/latest/drivers-orms/go/_index.md
> +[YugabyteDB installation steps](/latest/quick-start/install/macos).
All three of these sections could be a single compact bulleted list. See for example https://docs.yugabyte.com/latest/quick-start/build-apps/go/ysql-pg/ or the [Cloud version](https://docs.yugabyte.com/latest/yugabyte-cloud/cloud-quickstart/cloud-build-apps/cloud-ysql-go/) (which isn't quite as compact).

2022-02-17 05:28 UTC, polarweasel commented on docs/content/latest/drivers-orms/go/_index.md
> +We recommend using an integrated development environment (IDE) such as Intellij IDEA or
Make sure product names are spelled and capitalized correctly, like "IntelliJ IDEA".

Also, do we want to provide any details on the project the user is supposed to create?

2022-02-17 05:28 UTC, polarweasel commented on docs/content/latest/drivers-orms/go/_index.md
> +<br/> The cluster is free forever and includes enough resources to explore the core features available for
Avoid inline HTML where you can. In this case, instead of a `br`, just make these new paragraphs.

2022-02-17 05:28 UTC, polarweasel commented on docs/content/latest/drivers-orms/go/_index.md
> +and ORM section.<br/>
Should this be "drivers and ORMs" (plural) section?

2022-02-17 05:28 UTC, polarweasel commented on docs/content/latest/drivers-orms/go/gorm.md
> +for Go App development using the GORM ORM tool.
Let's just call it "the GORM tool", or even just "using GORM." :)
```suggestion
for Go App development using GORM.
```

2022-02-17 05:28 UTC, polarweasel commented on docs/content/latest/drivers-orms/go/gorm.md
> +
These headings aren't required.
```suggestion
```

2022-02-17 05:28 UTC, polarweasel commented on docs/content/latest/drivers-orms/go/gorm.md
> +In order to write data into YugabyteDB, use the `db.Create()` functions.
```suggestion
To write data into YugabyteDB, use the `db.Create()` function.
```

2022-02-17 05:28 UTC, polarweasel commented on docs/content/latest/drivers-orms/go/gorm.md
> +```golang
For all the snippets, tag them as "go" rather than "golang", just to be sure the highlighter catches them.
````suggestion
```go
````

2022-02-17 05:28 UTC, polarweasel commented on docs/content/latest/drivers-orms/go/gorm.md
> +In order to query data from YugabyteDB tables, execute the `db.Find()` function.
```suggestion
To query data from YugabyteDB tables, use the `db.Find()` function.
```

2022-02-17 05:28 UTC, polarweasel commented on docs/content/latest/drivers-orms/go/pg.md
> +    db := pg.Connect(opt)
Outdent this — I know it's indented in the app source, but indentation should usually be relative within a block.

2022-02-17 05:28 UTC, polarweasel commented on docs/content/latest/drivers-orms/go/pg.md
> +| Params | Description | Default |
```suggestion
| Parameter | Description | Default |
```

2022-02-17 05:28 UTC, polarweasel commented on docs/content/latest/drivers-orms/go/pgx.md
> +For Go Applications, most drivers provide database connectivity through the standard `database/sql`
```suggestion

For Go Applications, most drivers provide database connectivity through the standard `database/sql`
```

2022-02-17 05:28 UTC, polarweasel commented on docs/content/latest/drivers-orms/go/pgx.md
> +API. YugabyteDB supports [PGX Driver](https://github.com/jackc/pgx) and the
```suggestion
API. YugabyteDB supports the [PGX Driver](https://github.com/jackc/pgx) and the
```

2022-02-17 05:28 UTC, polarweasel commented on docs/content/latest/drivers-orms/go/pgx.md
> +You can import the PGX driver package by adding the following import statement in your Go code.
Most places, you can omit "you can".
```suggestion
Import the PGX driver package by adding the following import statement in your Go code.
```

2022-02-17 05:28 UTC, polarweasel commented on docs/content/latest/drivers-orms/go/pgx.md
> +PGX Connection url is in the format given below:
```suggestion
The PGX connection URL is in the following format:
```

2022-02-17 05:28 UTC, polarweasel commented on docs/content/latest/drivers-orms/go/pgx.md
> +Code snippet for connecting to YugabyteDB:
For all of the connection snippets... We suggest at the top that you create a Cloud cluster to do this stuff, but then we don't specify SSL parameters. That seems like something we ought to fix. (You're going to need cert paths for all of these, too.)

2022-02-17 05:28 UTC, polarweasel commented on docs/content/latest/drivers-orms/go/pgx.md
> +See this page - [PGX Driver](/latest/reference/drivers/go/pgx-reference/) - for more details.
```suggestion
See the [PGX Driver](/latest/reference/drivers/go/pgx-reference/) page for more details.
```

2022-02-17 05:28 UTC, polarweasel commented on docs/content/latest/reference/drivers/go/pgx-reference.md
> +    <a href="/latest/reference/drivers/go/pgx-reference/" class="nav-link active">
Another random place to point out: please use only relative URLs

2022-03-09 03:31 UTC, ashetkar commented on docs/content/latest/drivers-orms/go/_index.md
> +We recommend using an integrated development environment (IDE) such as Intellij IDEA or
Thanks. There is really no template that generates any skeleton project for Go, so this should be good.

2022-03-09 03:31 UTC, ashetkar commented on docs/content/latest/drivers-orms/go/gorm.md
> +```golang
Okay, will do. It wasn't showing anything different for me.

2022-03-09 04:04 UTC, ashetkar commented on docs/content/latest/drivers-orms/go/_index.md
> +section.
It saves you from horizontal scrolling while editing :) but I get your point. Unwrapped these at some locations.

2022-03-09 04:23 UTC, ashetkar commented on docs/content/latest/drivers-orms/go/pgx.md
> +Code snippet for connecting to YugabyteDB:
Yes, it is explained in details in pgx reference page, linked at the bottom.

2022-03-09 04:23 UTC, ashetkar commented on docs/content/latest/drivers-orms/go/pgx.md
> +Code snippet for connecting to YugabyteDB:
Yes, it is explained in details in pgx reference page, linked at the bottom.

2022-03-09 04:25 UTC, ashetkar commented on docs/content/latest/drivers-orms/go/_index.md
> +and ORM section.<br/>
Intention is to point user to specific driver (pq or pgx) and orm (gorm, go-pg) section.

2022-03-22 21:34 UTC, merged